version: '3.3'
services:
  nginx:
    image: nginx:1.17.4-alpine
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    volumes:
      - .:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/certbot/conf:/etc/letsencrypt
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - .:/application
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    
  php:
    build: ./docker/php/
    volumes:
      - .:/application
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/php.ini-development:/usr/local/etc/php/php.ini-development
      - ./docker/php/php.ini-production:/usr/local/etc/php/php.ini-production
      - ./docker/php/php.ini-production:/usr/local/etc/php/php.ini

    depends_on:
      - db
      - redis
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASS=secret
      - DB_NAME=laravel

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=ballnet
      - MYSQL_PASSWORD=ballnet

  redis:
    image: redis:5.0.6-alpine
    ports:
      - "6382:6379"

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"

volumes:
  db_data:
